version: "3.9"
services:
    bot:
        build:
            context: .
            dockerfile: bot/Dockerfile
        environment:
            SERVER_HOST: server
        container_name: tg-bot
        image: bot
    server:
        build:
            context: .
            dockerfile: server/Dockerfile
        image: server
        container_name: api-server
        ports:
            - 8080:8080