version: "3.9"
services:
    rabbitmq:
        platform: linux/x86_64
        container_name: rabbitmq
        image: rabbitmq:management-alpine
#        networks:
#            - microservices
        ports:
            - 5672:5672
            - 15672:15672
#        expose:
#            - 5672
#            - 15672
    bot: &base
        build:
            context: .
            dockerfile: bot/Dockerfile
        container_name: tg-bot
#        environment:
#            SERVER_HOST: server
#        image: bot
        command: python bot.py
#        networks:
#            - microservices
        depends_on:
            - rabbitmq
    amqp_daemon:
        <<: *base
#        build:
#            context: .
#            dockerfile: bot/Dockerfile.consumer
        container_name: tg-bot-consumer
#        image: bot
        command: uvicorn amqp_server:app
#        environment:
#            SERVER_HOST: server
#        networks:
#            - microservices
#        ports:
#            - 5000:5000
        depends_on:
            - rabbitmq
    server:
        build:
            context: .
            dockerfile: server/Dockerfile
        container_name: api-server
        image: server
#        networks:
#            - microservices
        ports:
            - 8080:8080
        depends_on:
            - rabbitmq
#
#networks:
#    microservices: