version: "3.8"
services:
    bot:
        build:
            context: .
            dockerfile: bot/Dockerfile
        image: bot
        container_name: tg-bot
    server:
        build:
            context: .
            dockerfile: server/Dockerfile
        image: server
        container_name: api-server
        ports:
            - 8080:8080
